# fly.toml app configuration file generated for fullstop3 on 2024-01-13T18:09:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstop3"
primary_region = "lhr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
