GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/65bf

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "New Person", 
    "number": "111-111-111"
}

###
PUT http://localhost:3001/api/persons/65c259d667b226dd5f3ec239
Content-Type: application/json

{ 
    "name": "Ne", 
    "number": "555555555555"
}

###
DELETE http://localhost:3001/api/persons/65be44